image: python

stages:
- build
- test
- deploy

build-job:
  stage: build
  script: 
    - python3 -v

test-area_calculator:
  stage: test
  script: 
    - python3 area_calculator_test.py

deploy-job:
  stage: deploy
  script:
    - echo "Finsished testing and deploying the application."

